-- Fabric notebook source

-- METADATA ********************

-- META {
-- META   "kernel_info": {
-- META     "name": "synapse_pyspark"
-- META   },
-- META   "dependencies": {
-- META     "lakehouse": {
-- META       "default_lakehouse": "201b9b7d-ca11-46b6-81e8-feeba4c99642",
-- META       "default_lakehouse_name": "permitting_lakehouse",
-- META       "default_lakehouse_workspace_id": "79dafa8a-b966-4240-80f7-2e9d46baa5c3",
-- META       "known_lakehouses": [
-- META         {
-- META           "id": "201b9b7d-ca11-46b6-81e8-feeba4c99642"
-- META         }
-- META       ]
-- META     }
-- META   }
-- META }

-- CELL ********************

DROP SCHEMA tantalis_staging CASCADE;


-- METADATA ********************

-- META {
-- META   "language": "sparksql",
-- META   "language_group": "synapse_pyspark"
-- META }

-- CELL ********************

CREATE OR ALTER VIEW tantalis_staging.tantalis_auths_vw AS
SELECT DISTINCT
       DT.APPLICATION_TYPE_CDE,
       --DTS.CODE_CHR_STAGE,
       TSG.STAGE_NME,
       --CAST (DT.TYPE_SID AS INT) AS TYPE_SID,
       TAV.TYPE_NME,
       --CAST (DT.SUBTYPE_SID AS INT) AS SUBTYPE_SID,
       TAS.SUBTYPE_NME,
       TAP.PURPOSE_NME,
       TASU.SUBPURPOSE_NME,
       TD.ACTIVATION_CDE,
       --DTS.CODE_CHR_STATUS,
       TST.STATUS_NME,
       --DTS.CODE_CHR_REASON,
       TR.REASON_DSC,
       CAST (DT.DISPOSITION_SID AS INT) AS DISPOSITION_SID,
       CAST (DT.DISPOSITION_TRANSACTION_SID AS INT) AS DISPOSITION_TRANSACTION_SID,
       DT.REPLMNT_FOR_DISP_TRANS_SID,
       TD.FILE_CHR,
       CAST (DT.ORG_UNIT_SID AS INT) AS ORG_UNIT_SID,
       DT.MANAGING_AGENCY,
       O.UNIT_NAME,
       TDO.NAME AS DISTRICT_OFFICE,
       DT.RECEIVED_DAT,
       TASKS.LAND_STATUS_DAT,
       TASKS.REPORTED_DAT,
       TASKS.ADJUDICATED_DAT,
       TASKS.DISALLOWED_DAT,
       TASKS.OFFERED_DAT,
       TASKS.OFFER_NOT_ACCEPTED_DAT,
       DT.COMMENCEMENT_DAT,
       DT.EXPIRY_DAT,
       TASKS.CANCELED_DAT,
       DTS.EFFECTIVE_DAT,
       DT.REVIEW_DAT
       --DT.COMPLEXITY_LEVEL_CDE,
       --DT.CROWN_GRANT_YRN
FROM tantalis_replication.ta_disposition_transactions DT
JOIN tantalis_replication.ta_organization_units O
    ON O.ORG_UNIT_SID = DT.ORG_UNIT_SID
JOIN tantalis_replication.ta_dispositions TD
    ON TD.DISPOSITION_SID = DT.DISPOSITION_SID
JOIN tantalis_replication.ta_disp_trans_statuses DTS
    ON DTS.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
   AND DTS.EXPIRY_DAT IS NULL
LEFT JOIN (
       SELECT  DISPOSITION_TRANSACTION_SID,
               MAX(LAND_STATUS_DAT)        AS LAND_STATUS_DAT,
               MAX(REPORTED_DAT)           AS REPORTED_DAT,
               MAX(ADJUDICATED_DAT)        AS ADJUDICATED_DAT,
               MAX(DISALLOWED_DAT)         AS DISALLOWED_DAT,
               MAX(OFFERED_DAT)            AS OFFERED_DAT,
               MAX(OFFER_NOT_ACCEPTED_DAT) AS OFFER_NOT_ACCEPTED_DAT,
               MAX(CANCELED_DAT)           AS CANCELED_DAT
       FROM tantalis_replication.ta_disp_trans_tasks
       GROUP BY DISPOSITION_TRANSACTION_SID
) TASKS
    ON TASKS.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
LEFT JOIN tantalis_replication.ta_available_types TAV
    ON TAV.TYPE_SID = DT.TYPE_SID
LEFT JOIN tantalis_replication.ta_available_subtypes TAS
    ON TAS.TYPE_SID = DT.TYPE_SID
   AND TAS.SUBTYPE_SID = DT.SUBTYPE_SID
LEFT JOIN tantalis_replication.ta_available_purposes TAP
    ON TAP.PURPOSE_SID = DT.PURPOSE_SID
LEFT JOIN tantalis_replication.ta_available_subpurposes TASU
    ON TASU.PURPOSE_SID = DT.PURPOSE_SID
   AND TASU.SUBPURPOSE_SID = DT.SUBPURPOSE_SID
LEFT JOIN tantalis_replication.ta_district_offices TDO
    ON DT.DISTRICT_OFFICE_SID = TDO.DISTRICT_OFFICE_SID
LEFT JOIN tantalis_replication.ta_status TST
        ON DTS.CODE_CHR_STATUS = TST.CODE_CHR
LEFT JOIN tantalis_replication.ta_stages TSG
    ON DTS.CODE_CHR_STAGE = TSG.CODE_CHR
LEFT JOIN tantalis_replication.ta_reasons TR
    ON DTS.CODE_CHR_REASON = TR.CODE_CHR
WHERE DT.RECEIVED_DAT >=  '2014-04-01'
  AND DT.APPLICATION_TYPE_CDE = 'NEW'
  AND DT.TYPE_SID <> 51
  AND NOT (DT.TYPE_SID = 1 AND DT.SUBTYPE_SID = 101);


-- METADATA ********************

-- META {
-- META   "language": "sql",
-- META   "language_group": "sqldatawarehouse",
-- META   "frozen": false,
-- META   "editable": true
-- META }

-- CELL ********************

CREATE OR ALTER VIEW  tantalis_staging.tantalis_vfcbc_auths_vw
AS SELECT
			lv.APPLICANT,
			lv.SUBMITTER,
			lv.AUTHORIZATIONTYPE,
			lv.APPLICATIONTYPE,
            lt.STAGE_NME,
			lt.TYPE_NME,
			lt.SUBTYPE_NME,
			lt.PURPOSE_NME,
			lt.SUBPURPOSE_NME,
            lv.STATUS AS STATUS_V,
			REPLACE(STATUSSHOWNTOCLIENT, '<br>', '') AS STATUS_VISIBLE_V,
			lt.ACTIVATION_CDE,
			lt.STATUS_NME,
			lt.REASON_DSC,
            lv.TRACKINGNUMBER,
			lv.ATSLINKID,
			lv.ATSAUTHORIZATIONNUMBER,
			lv.ATSPROJECTNUMBER,
			lv.LANDSFILENUMBER,
			lv.DISPOSITION_TRANSACTION_SID AS DISPOSITION_TRANSACTION_SID_V,
			lt.DISPOSITION_SID,
			lt.DISPOSITION_TRANSACTION_SID,
			lt.REPLMNT_FOR_DISP_TRANS_SID,
			lt.FILE_CHR,
            lv.BUSINESSAREA,
			lv.BUSINESSAREANUMBER,
			lt.ORG_UNIT_SID,
			lt.MANAGING_AGENCY,
            lv.OFFICE,
			lt.UNIT_NAME,
			lt.DISTRICT_OFFICE,
            lv.CREATEDDATE AS CREATEDDATE_V,
			lv.SUBMITTEDDATE AS SUBMITTEDDATE_V,
			lv.RECEIVEDDATE AS RECEIVEDDATE_V,
			lv.DATECOMPLETED AS DATECOMPLETED_V,
			lt.RECEIVED_DAT,
			lt.LAND_STATUS_DAT,
			lt.REPORTED_DAT,
			lt.ADJUDICATED_DAT,
			lt.DISALLOWED_DAT,
			lt.OFFERED_DAT,
			lt.OFFER_NOT_ACCEPTED_DAT,
			lt.COMMENCEMENT_DAT,
			lt.EXPIRY_DAT,
			lt.CANCELED_DAT,
			lt.EFFECTIVE_DAT,
			lt.REVIEW_DAT
FROM vfcbc_staging.vfcbc_lands_auths_vw lv, tantalis_staging.tantalis_auths_vw lt 
WHERE lv.DISPOSITION_TRANSACTION_SID = lt.DISPOSITION_TRANSACTION_SID;

-- METADATA ********************

-- META {
-- META   "language": "sql",
-- META   "language_group": "sqldatawarehouse"
-- META }

-- CELL ********************

CREATE OR ALTER VIEW tantalis_staging.tantalis_vfcbc_only_vw
AS
WITH
vfcbc_raw AS (
    SELECT
        a.JOBID,
        a.TRACKINGNUMBER,
        a.ATSLINKID,
        b.ATSAUTHORIZATIONNUMBER,
        a.ATSPROJECTNUMBER,
        b.LANDSFILENUMBER,
        b.DISPOSITION_TRANSACTION_STRING,
        a.BUSINESSAREA,
        a.BUSINESSAREANUMBER,
        a.OFFICE,
        a.APPLICANT,
        a.SUBMITTER,
        a.AUTHORIZATIONTYPE,
        a.APPLICATIONTYPE,
        a.STATUS,
        a.STATUSSHOWNTOCLIENT,
        a.CREATEDDATE,
        a.SUBMITTEDDATE,
        a.RECEIVEDDATE,
        a.DATECOMPLETED
    FROM vfcbc_replication.vfcbc_application_vw a
    LEFT JOIN vfcbc_replication.vfcbc_atsnumber_vw b
        ON a.ATSLINKID = b.ATSLINKID
    WHERE a.BUSINESSAREA = 'Crown Land Adjudication (vFCBC)'
),
vfcbc_norm AS (
    SELECT
        r.*,
        TRY_CONVERT(
            BIGINT,
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.DISPOSITION_TRANSACTION_STRING))), '')
        ) AS VFCBC_DISPOSITION_TRANSACTION_SID,
        COALESCE(
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.JOBID))), ''),
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.TRACKINGNUMBER))), ''),
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.ATSLINKID))), ''),
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.ATSAUTHORIZATIONNUMBER))), '')
        ) AS VFCBC_PIESID
    FROM vfcbc_raw r
),
tantalis_keys AS (
    SELECT DISTINCT
        TRY_CONVERT(BIGINT, DT.DISPOSITION_TRANSACTION_SID) AS DISPOSITION_TRANSACTION_SID
    FROM tantalis_replication.ta_disposition_transactions DT
    WHERE DT.RECEIVED_DAT >= '2014-04-01'
      AND DT.APPLICATION_TYPE_CDE = 'NEW'
      AND DT.TYPE_SID <> 51
      AND NOT (DT.TYPE_SID = 1 AND DT.SUBTYPE_SID = 101)
      AND TRY_CONVERT(BIGINT, DT.DISPOSITION_TRANSACTION_SID) IS NOT NULL
      AND EXISTS (
          SELECT 1
          FROM tantalis_replication.ta_dispositions TD
          WHERE TD.DISPOSITION_SID = DT.DISPOSITION_SID
      )
      AND EXISTS (
          SELECT 1
          FROM tantalis_replication.ta_organization_units O
          WHERE O.ORG_UNIT_SID = DT.ORG_UNIT_SID
      )
      AND EXISTS (
          SELECT 1
          FROM tantalis_replication.ta_disp_trans_statuses DTS
          WHERE DTS.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
            AND DTS.EXPIRY_DAT IS NULL
      )
),
vfcbc_only AS (
    SELECT
        v.*
    FROM vfcbc_norm v
    WHERE NOT EXISTS (
        SELECT 1
        FROM tantalis_keys t
        WHERE t.DISPOSITION_TRANSACTION_SID = v.VFCBC_DISPOSITION_TRANSACTION_SID
    )
),
vfcbc_ranked AS (
    SELECT
        v.*,
        ROW_NUMBER() OVER (
            PARTITION BY v.VFCBC_PIESID
            ORDER BY
                CASE
                    WHEN v.VFCBC_DISPOSITION_TRANSACTION_SID IS NOT NULL THEN 1
                    ELSE 0
                END DESC,
                COALESCE(
                    TRY_CONVERT(DATETIME2(0), v.DATECOMPLETED),
                    TRY_CONVERT(DATETIME2(0), v.RECEIVEDDATE),
                    TRY_CONVERT(DATETIME2(0), v.SUBMITTEDDATE),
                    TRY_CONVERT(DATETIME2(0), v.CREATEDDATE)
                ) DESC,
                NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), v.ATSAUTHORIZATIONNUMBER))), '') DESC,
                NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), v.TRACKINGNUMBER))), '') DESC,
                NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), v.ATSLINKID))), '') DESC
        ) AS vfcbc_rn
    FROM vfcbc_only v
    WHERE v.VFCBC_PIESID IS NOT NULL
)
SELECT
    v.VFCBC_PIESID AS PIESID,
    CAST('ITSM-6117' AS VARCHAR(50)) AS system_id,

    TRY_CONVERT(DATETIME2(0), v.CREATEDDATE) AS CREATEDDATE,
    TRY_CONVERT(DATETIME2(0), v.SUBMITTEDDATE) AS SUBMITTEDDATE,
    TRY_CONVERT(DATETIME2(0), v.RECEIVEDDATE) AS APPLICATION_RECEIVED_DATE,

    CAST(NULL AS DATETIME2(0)) AS APPLICATION_ACCEPTED_DATE,
    CAST(NULL AS DATETIME2(0)) AS APPLICATION_REJECTED_DATE,

    CAST(NULL AS DATETIME2(0)) AS ADJUDICATION_DATE,
    CAST(NULL AS DATETIME2(0)) AS ADJUDICATED_DAT,
    CAST(NULL AS DATETIME2(0)) AS DISALLOWED_DAT,
    CAST(NULL AS DATETIME2(0)) AS OFFERED_DAT,
    CAST(NULL AS DATETIME2(0)) AS OFFER_NOT_ACCEPTED_DAT,

    TRY_CONVERT(DATETIME2(0), v.DATECOMPLETED) AS COMPLETED_DAT,

    CAST(NULL AS DATETIME2(0)) AS CANCELED_DAT,
    CAST(NULL AS DATETIME2(0)) AS EXPIRY_DAT,
    CAST(NULL AS DATETIME2(0)) AS LAND_STATUS_DAT,
    CAST(NULL AS DATETIME2(0)) AS REPORTED_DAT,

    CAST(NULL AS DATETIME2(0)) AS FIRST_NATION_START_DATE,
    CAST(NULL AS DATETIME2(0)) AS FIRST_NATION_COMPLETION_DATE,

    CAST(NULL AS VARCHAR(20)) AS AUTHORIZATION_STATUS_CODE,
    CAST(NULL AS VARCHAR(20)) AS ATHN_CLOSE_REASON_CODE,

    CAST(NULL AS VARCHAR(20)) AS CODE_CHR_STATUS,

    NULLIF(
        LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), v.ATSAUTHORIZATIONNUMBER))),
        ''
    ) AS ATSAUTHORIZATIONNUMBER,

    v.JOBID,
    v.APPLICANT,
    v.SUBMITTER,
    v.AUTHORIZATIONTYPE,
    v.APPLICATIONTYPE,

    CAST(NULL AS VARCHAR(20)) AS APPLICATION_TYPE_CDE,
    CAST(NULL AS VARCHAR(200)) AS STAGE_NME,
    CAST(NULL AS VARCHAR(200)) AS TYPE_NME,
    CAST(NULL AS VARCHAR(200)) AS SUBTYPE_NME,
    CAST(NULL AS VARCHAR(200)) AS PURPOSE_NME,
    CAST(NULL AS VARCHAR(200)) AS SUBPURPOSE_NME,

    v.STATUS AS STATUS_V,
    REPLACE(
        TRY_CONVERT(VARCHAR(MAX), v.STATUSSHOWNTOCLIENT),
        '<br>',
        ''
    ) AS STATUS_VISIBLE_V,

    CAST(NULL AS VARCHAR(50)) AS ACTIVATION_CDE,
    CAST(NULL AS VARCHAR(200)) AS STATUS_NME,
    CAST(NULL AS VARCHAR(500)) AS REASON_DSC,

    v.TRACKINGNUMBER,
    v.ATSLINKID,
    v.ATSAUTHORIZATIONNUMBER AS ATSAUTHORIZATIONNUMBER_RAW,
    v.ATSPROJECTNUMBER,
    v.LANDSFILENUMBER,

    v.DISPOSITION_TRANSACTION_STRING,
    v.VFCBC_DISPOSITION_TRANSACTION_SID AS DISPOSITION_TRANSACTION_SID_V,
    CAST(NULL AS BIGINT) AS DISPOSITION_SID,
    CAST(NULL AS BIGINT) AS DISPOSITION_TRANSACTION_SID,
    CAST(NULL AS BIGINT) AS REPLMNT_FOR_DISP_TRANS_SID,
    CAST(NULL AS VARCHAR(100)) AS FILE_CHR,

    v.BUSINESSAREA,
    v.BUSINESSAREANUMBER,
    CAST(NULL AS BIGINT) AS ORG_UNIT_SID,
    CAST(NULL AS VARCHAR(200)) AS MANAGING_AGENCY,

    v.OFFICE,
    CAST(NULL AS VARCHAR(200)) AS UNIT_NAME,
    CAST(NULL AS VARCHAR(200)) AS DISTRICT_OFFICE,

    v.CREATEDDATE AS CREATEDDATE_V,
    v.SUBMITTEDDATE AS SUBMITTEDDATE_V,
    v.RECEIVEDDATE AS RECEIVEDDATE_V,
    v.DATECOMPLETED AS DATECOMPLETED_V,

    CAST(NULL AS DATETIME2(0)) AS RECEIVED_DAT,
    CAST(NULL AS DATETIME2(0)) AS COMMENCEMENT_DAT,
    CAST(NULL AS DATETIME2(0)) AS EFFECTIVE_DAT,
    CAST(NULL AS DATETIME2(0)) AS REVIEW_DAT,

    CAST(NULL AS DATETIME2(0)) AS LAND_STATUS_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS REPORTED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS ADJUDICATED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS DISALLOWED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS OFFERED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS OFFER_NOT_ACCEPTED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS EXPIRY_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS CANCELED_DAT_RAW,

    CAST(NULL AS VARCHAR(20)) AS CODE_CHR_STAGE,
    CAST(NULL AS VARCHAR(20)) AS CODE_CHR_STATUS_RAW,
    CAST(NULL AS VARCHAR(20)) AS CODE_CHR_REASON

FROM vfcbc_ranked v
WHERE v.vfcbc_rn = 1;

-- METADATA ********************

-- META {
-- META   "language": "sparksql",
-- META   "language_group": "synapse_pyspark"
-- META }
