# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# CELL ********************

CREATE OR ALTER VIEW tantalis_staging.tantalis_vfcbc_only_vw
AS
WITH
vfcbc_raw AS (
    SELECT
        a.JOBID,
        a.TRACKINGNUMBER,
        a.ATSLINKID,
        b.ATSAUTHORIZATIONNUMBER,
        a.ATSPROJECTNUMBER,
        b.LANDSFILENUMBER,
        b.DISPOSITION_TRANSACTION_STRING,
        a.BUSINESSAREA,
        a.BUSINESSAREANUMBER,
        a.OFFICE,
        a.APPLICANT,
        a.SUBMITTER,
        a.AUTHORIZATIONTYPE,
        a.APPLICATIONTYPE,
        a.STATUS,
        a.STATUSSHOWNTOCLIENT,
        a.CREATEDDATE,
        a.SUBMITTEDDATE,
        a.RECEIVEDDATE,
        a.DATECOMPLETED
    FROM vfcbc_replication.vfcbc_application_vw a
    LEFT JOIN vfcbc_replication.vfcbc_atsnumber_vw b
        ON a.ATSLINKID = b.ATSLINKID
    WHERE a.BUSINESSAREA = 'Crown Land Adjudication (vFCBC)'
),
vfcbc_norm AS (
    SELECT
        r.*,
        TRY_CONVERT(
            BIGINT,
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.DISPOSITION_TRANSACTION_STRING))), '')
        ) AS VFCBC_DISPOSITION_TRANSACTION_SID,
        COALESCE(
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.JOBID))), ''),
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.TRACKINGNUMBER))), ''),
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.ATSLINKID))), ''),
            NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), r.ATSAUTHORIZATIONNUMBER))), '')
        ) AS VFCBC_PIESID
    FROM vfcbc_raw r
),
tantalis_keys AS (
    SELECT DISTINCT
        TRY_CONVERT(BIGINT, DT.DISPOSITION_TRANSACTION_SID) AS DISPOSITION_TRANSACTION_SID
    FROM tantalis_replication.ta_disposition_transactions DT
    WHERE DT.RECEIVED_DAT >= '2014-04-01'
      AND DT.APPLICATION_TYPE_CDE = 'NEW'
      AND DT.TYPE_SID <> 51
      AND NOT (DT.TYPE_SID = 1 AND DT.SUBTYPE_SID = 101)
      AND TRY_CONVERT(BIGINT, DT.DISPOSITION_TRANSACTION_SID) IS NOT NULL
      AND EXISTS (
          SELECT 1
          FROM tantalis_replication.ta_dispositions TD
          WHERE TD.DISPOSITION_SID = DT.DISPOSITION_SID
      )
      AND EXISTS (
          SELECT 1
          FROM tantalis_replication.ta_organization_units O
          WHERE O.ORG_UNIT_SID = DT.ORG_UNIT_SID
      )
      AND EXISTS (
          SELECT 1
          FROM tantalis_replication.ta_disp_trans_statuses DTS
          WHERE DTS.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
            AND DTS.EXPIRY_DAT IS NULL
      )
),
vfcbc_only AS (
    SELECT
        v.*
    FROM vfcbc_norm v
    WHERE NOT EXISTS (
        SELECT 1
        FROM tantalis_keys t
        WHERE t.DISPOSITION_TRANSACTION_SID = v.VFCBC_DISPOSITION_TRANSACTION_SID
    )
),
vfcbc_ranked AS (
    SELECT
        v.*,
        ROW_NUMBER() OVER (
            PARTITION BY v.VFCBC_PIESID
            ORDER BY
                CASE
                    WHEN v.VFCBC_DISPOSITION_TRANSACTION_SID IS NOT NULL THEN 1
                    ELSE 0
                END DESC,
                COALESCE(
                    TRY_CONVERT(DATETIME2(0), v.DATECOMPLETED),
                    TRY_CONVERT(DATETIME2(0), v.RECEIVEDDATE),
                    TRY_CONVERT(DATETIME2(0), v.SUBMITTEDDATE),
                    TRY_CONVERT(DATETIME2(0), v.CREATEDDATE)
                ) DESC,
                NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), v.ATSAUTHORIZATIONNUMBER))), '') DESC,
                NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), v.TRACKINGNUMBER))), '') DESC,
                NULLIF(LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), v.ATSLINKID))), '') DESC
        ) AS vfcbc_rn
    FROM vfcbc_only v
    WHERE v.VFCBC_PIESID IS NOT NULL
)
SELECT
    v.VFCBC_PIESID AS PIESID,
    CAST('ITSM-6072' AS VARCHAR(50)) AS system_id,

    TRY_CONVERT(DATETIME2(0), v.CREATEDDATE) AS CREATEDDATE,
    TRY_CONVERT(DATETIME2(0), v.SUBMITTEDDATE) AS SUBMITTEDDATE,
    TRY_CONVERT(DATETIME2(0), v.RECEIVEDDATE) AS APPLICATION_RECEIVED_DATE,

    CAST(NULL AS DATETIME2(0)) AS APPLICATION_ACCEPTED_DATE,
    CAST(NULL AS DATETIME2(0)) AS APPLICATION_REJECTED_DATE,

    CAST(NULL AS DATETIME2(0)) AS ADJUDICATION_DATE,
    CAST(NULL AS DATETIME2(0)) AS ADJUDICATED_DAT,
    CAST(NULL AS DATETIME2(0)) AS DISALLOWED_DAT,
    CAST(NULL AS DATETIME2(0)) AS OFFERED_DAT,
    CAST(NULL AS DATETIME2(0)) AS OFFER_NOT_ACCEPTED_DAT,

    TRY_CONVERT(DATETIME2(0), v.DATECOMPLETED) AS COMPLETED_DAT,

    CAST(NULL AS DATETIME2(0)) AS CANCELED_DAT,
    CAST(NULL AS DATETIME2(0)) AS EXPIRY_DAT,
    CAST(NULL AS DATETIME2(0)) AS LAND_STATUS_DAT,
    CAST(NULL AS DATETIME2(0)) AS REPORTED_DAT,

    CAST(NULL AS DATETIME2(0)) AS FIRST_NATION_START_DATE,
    CAST(NULL AS DATETIME2(0)) AS FIRST_NATION_COMPLETION_DATE,

    CAST(NULL AS VARCHAR(20)) AS AUTHORIZATION_STATUS_CODE,
    CAST(NULL AS VARCHAR(20)) AS ATHN_CLOSE_REASON_CODE,

    CAST(NULL AS VARCHAR(20)) AS CODE_CHR_STATUS,

    NULLIF(
        LTRIM(RTRIM(TRY_CONVERT(VARCHAR(100), v.ATSAUTHORIZATIONNUMBER))),
        ''
    ) AS ATSAUTHORIZATIONNUMBER,

    v.JOBID,
    v.APPLICANT,
    v.SUBMITTER,
    v.AUTHORIZATIONTYPE,
    v.APPLICATIONTYPE,

    CAST(NULL AS VARCHAR(20)) AS APPLICATION_TYPE_CDE,
    CAST(NULL AS VARCHAR(200)) AS STAGE_NME,
    CAST(NULL AS VARCHAR(200)) AS TYPE_NME,
    CAST(NULL AS VARCHAR(200)) AS SUBTYPE_NME,
    CAST(NULL AS VARCHAR(200)) AS PURPOSE_NME,
    CAST(NULL AS VARCHAR(200)) AS SUBPURPOSE_NME,

    v.STATUS AS STATUS_V,
    REPLACE(
        TRY_CONVERT(VARCHAR(MAX), v.STATUSSHOWNTOCLIENT),
        '<br>',
        ''
    ) AS STATUS_VISIBLE_V,

    CAST(NULL AS VARCHAR(50)) AS ACTIVATION_CDE,
    CAST(NULL AS VARCHAR(200)) AS STATUS_NME,
    CAST(NULL AS VARCHAR(500)) AS REASON_DSC,

    v.TRACKINGNUMBER,
    v.ATSLINKID,
    v.ATSAUTHORIZATIONNUMBER AS ATSAUTHORIZATIONNUMBER_RAW,
    v.ATSPROJECTNUMBER,
    v.LANDSFILENUMBER,

    v.DISPOSITION_TRANSACTION_STRING,
    v.VFCBC_DISPOSITION_TRANSACTION_SID AS DISPOSITION_TRANSACTION_SID_V,
    CAST(NULL AS BIGINT) AS DISPOSITION_SID,
    CAST(NULL AS BIGINT) AS DISPOSITION_TRANSACTION_SID,
    CAST(NULL AS BIGINT) AS REPLMNT_FOR_DISP_TRANS_SID,
    CAST(NULL AS VARCHAR(100)) AS FILE_CHR,

    v.BUSINESSAREA,
    v.BUSINESSAREANUMBER,
    CAST(NULL AS BIGINT) AS ORG_UNIT_SID,
    CAST(NULL AS VARCHAR(200)) AS MANAGING_AGENCY,

    v.OFFICE,
    CAST(NULL AS VARCHAR(200)) AS UNIT_NAME,
    CAST(NULL AS VARCHAR(200)) AS DISTRICT_OFFICE,

    v.CREATEDDATE AS CREATEDDATE_V,
    v.SUBMITTEDDATE AS SUBMITTEDDATE_V,
    v.RECEIVEDDATE AS RECEIVEDDATE_V,
    v.DATECOMPLETED AS DATECOMPLETED_V,

    CAST(NULL AS DATETIME2(0)) AS RECEIVED_DAT,
    CAST(NULL AS DATETIME2(0)) AS COMMENCEMENT_DAT,
    CAST(NULL AS DATETIME2(0)) AS EFFECTIVE_DAT,
    CAST(NULL AS DATETIME2(0)) AS REVIEW_DAT,

    CAST(NULL AS DATETIME2(0)) AS LAND_STATUS_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS REPORTED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS ADJUDICATED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS DISALLOWED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS OFFERED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS OFFER_NOT_ACCEPTED_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS EXPIRY_DAT_RAW,
    CAST(NULL AS DATETIME2(0)) AS CANCELED_DAT_RAW,

    CAST(NULL AS VARCHAR(20)) AS CODE_CHR_STAGE,
    CAST(NULL AS VARCHAR(20)) AS CODE_CHR_STATUS_RAW,
    CAST(NULL AS VARCHAR(20)) AS CODE_CHR_REASON

FROM vfcbc_ranked v
WHERE v.vfcbc_rn = 1;

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

IF OBJECT_ID('tantalis_staging.vw_ta_disposition_merged', 'V') IS NOT NULL
    DROP VIEW tantalis_staging.vw_ta_disposition_merged;
GO

CREATE VIEW tantalis_staging.vw_ta_disposition_merged AS
SELECT DISTINCT
       DT.APPLICATION_TYPE_CDE,
       DT.COMMENCEMENT_DAT,
       DT.COMPLEXITY_LEVEL_CDE,
       DT.CROWN_GRANT_YRN,
       DT.DISPOSITION_SID,
       DT.DISPOSITION_TRANSACTION_SID,
       DT.EXPIRY_DAT,
       DT.MANAGING_AGENCY,
       DT.ORG_UNIT_SID,
       DT.RECEIVED_DAT,
       DT.REPLMNT_FOR_DISP_TRANS_SID,
       DT.REVIEW_DAT,
       DT.SUBTYPE_SID,
       DT.TYPE_SID,
       O.UNIT_NAME,
       TD.ACTIVATION_CDE,
       TD.FILE_CHR,
       DTS.CODE_CHR_STATUS,
       DTS.CODE_CHR_STAGE,
       DTS.EFFECTIVE_DAT,
       DTS.CODE_CHR_REASON,
       TAV.TYPE_NME,
       TAS.SUBTYPE_NME,
       TAP.PURPOSE_NME,
       TASU.SUBPURPOSE_NME,
       TDO.NAME AS DISTRICT_OFFICE,
       TASKS.LAND_STATUS_DAT,
       TASKS.REPORTED_DAT,
       TASKS.ADJUDICATED_DAT,
       TASKS.DISALLOWED_DAT,
       TASKS.OFFERED_DAT,
       TASKS.OFFER_NOT_ACCEPTED_DAT,
       TASKS.COMPLETED_DAT,
       TASKS.CANCELED_DAT
FROM tantalis_replication.ta_disposition_transactions DT
JOIN tantalis_replication.ta_organization_units O
    ON O.ORG_UNIT_SID = DT.ORG_UNIT_SID
JOIN tantalis_replication.ta_dispositions TD
    ON TD.DISPOSITION_SID = DT.DISPOSITION_SID
JOIN tantalis_replication.ta_disp_trans_statuses DTS
    ON DTS.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
   AND DTS.EXPIRY_DAT IS NULL
LEFT JOIN (
       SELECT  DISPOSITION_TRANSACTION_SID,
               MAX(LAND_STATUS_DAT)        AS LAND_STATUS_DAT,
               MAX(REPORTED_DAT)           AS REPORTED_DAT,
               MAX(ADJUDICATED_DAT)        AS ADJUDICATED_DAT,
               MAX(DISALLOWED_DAT)         AS DISALLOWED_DAT,
               MAX(OFFERED_DAT)            AS OFFERED_DAT,
               MAX(OFFER_NOT_ACCEPTED_DAT) AS OFFER_NOT_ACCEPTED_DAT,
               MAX(COMPLETED_DAT)          AS COMPLETED_DAT,
               MAX(CANCELED_DAT)           AS CANCELED_DAT
       FROM tantalis_replication.ta_disp_trans_tasks
       GROUP BY DISPOSITION_TRANSACTION_SID
) TASKS
    ON TASKS.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
LEFT JOIN tantalis_replication.ta_available_types TAV
    ON TAV.TYPE_SID = DT.TYPE_SID
LEFT JOIN tantalis_replication.ta_available_subtypes TAS
    ON TAS.TYPE_SID = DT.TYPE_SID
   AND TAS.SUBTYPE_SID = DT.SUBTYPE_SID
LEFT JOIN tantalis_replication.ta_available_purposes TAP
    ON TAP.PURPOSE_SID = DT.PURPOSE_SID
LEFT JOIN tantalis_replication.ta_available_subpurposes TASU
    ON TASU.PURPOSE_SID = DT.PURPOSE_SID
   AND TASU.SUBPURPOSE_SID = DT.SUBPURPOSE_SID
LEFT JOIN tantalis_replication.ta_district_offices TDO
    ON DT.DISTRICT_OFFICE_SID = TDO.DISTRICT_OFFICE_SID
WHERE CAST(DT.RECEIVED_DAT AS DATE) >= '2014-04-01'
  AND DT.APPLICATION_TYPE_CDE = 'NEW'
  AND DT.TYPE_SID <> 51
  AND NOT (DT.TYPE_SID = 1 AND DT.SUBTYPE_SID = 101);
GO

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

CREATE OR ALTER VIEW tantalis_staging.ta_vfcbc_merged AS
SELECT

    a.JOBID,
    a.TRACKINGNUMBER,
    a.BUSINESSAREANUMBER AS BUSINESSAREANUMBER_CORAL,
    a.ATSLINKID,
    a.LANDSFILENUMBER,
    a.SUBMITTER,
    a.APPLICANT,
    a.AUTHORIZATIONTYPE,
    a.APPLICATIONTYPE,
    a.CREATEDDATE,
    a.STATUS,
    a.OFFICE,
    a.BUSINESSAREA,
    a.SUBMITTEDDATE,
    a.RECEIVEDDATE,
    a.DATECOMPLETED,


    b.ATSAUTHORIZATIONNUMBER,
    b.LANDSFILENUMBER AS ATS_LANDSFILENUMBER,
    b.DISPOSITION_TRANSACTION_SID,


    c.BUSINESSAREANUMBER AS BUSINESSAREANUMBER
FROM vfcbc_replication.vfcbc_application_vw a
LEFT JOIN vfcbc_replication.vfcbc_atsnumber_vw b
    ON a.ATSLINKID = b.ATSLINKID
LEFT JOIN vfcbc_replication.vfcbc_crownlandtenureapparea c
    ON b.ATSAUTHORIZATIONNUMBER = c.ATSAUTHORIZATIONNUMBER
WHERE a.BUSINESSAREA = 'Crown Land Adjudication (vFCBC)';

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

IF SCHEMA_ID('ats_staging') IS NULL
BEGIN
    EXEC('CREATE SCHEMA ats_staging');
END;
GO

DROP VIEW IF EXISTS ats_staging.ats_authorizations_on_hold_staging;
GO

CREATE VIEW ats_staging.ats_authorizations_on_hold_staging
AS
WITH deduped AS (
    SELECT
        AUTHORIZATION_ON_HOLD_ID,
        ATHN_ON_HOLD_REASON_CODE,
        AUTHORIZATION_ID,
        CURRENT_ON_HOLD_IND,
        WHO_CREATED,
        WHEN_CREATED,
        ON_HOLD_START_DATE,
        ON_HOLD_END_DATE,
        ON_HOLD_NOTES,
        REMOVED_BY,
        WHO_UPDATED,
        WHEN_UPDATED,
        PARTNER_AGENCY_ID,
        ROW_NUMBER() OVER (
            PARTITION BY
                ATHN_ON_HOLD_REASON_CODE,
                AUTHORIZATION_ID,
                ON_HOLD_START_DATE,
                ON_HOLD_END_DATE
            ORDER BY
                AUTHORIZATION_ON_HOLD_ID
        ) AS rn
    FROM ats_replication.ats_authorizations_on_hold
)
SELECT
    AUTHORIZATION_ON_HOLD_ID,
    ATHN_ON_HOLD_REASON_CODE,
    AUTHORIZATION_ID,
    CURRENT_ON_HOLD_IND,
    WHO_CREATED,
    WHEN_CREATED,
    ON_HOLD_START_DATE,
    ON_HOLD_END_DATE,
    ON_HOLD_NOTES,
    REMOVED_BY,
    WHO_UPDATED,
    WHEN_UPDATED,
    PARTNER_AGENCY_ID
FROM deduped
WHERE rn = 1;
GO

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
