-- Fabric notebook source

-- METADATA ********************

-- META {
-- META   "kernel_info": {
-- META     "name": "synapse_pyspark"
-- META   },
-- META   "dependencies": {
-- META     "lakehouse": {
-- META       "default_lakehouse": "201b9b7d-ca11-46b6-81e8-feeba4c99642",
-- META       "default_lakehouse_name": "pmt_lakehouse",
-- META       "default_lakehouse_workspace_id": "79dafa8a-b966-4240-80f7-2e9d46baa5c3",
-- META       "known_lakehouses": [
-- META         {
-- META           "id": "201b9b7d-ca11-46b6-81e8-feeba4c99642"
-- META         }
-- META       ]
-- META     }
-- META   }
-- META }

-- MARKDOWN ********************

-- # Create materialized lake views 
-- 1. Use this notebook to create materialized lake views. 
-- 2. Select **Run all** to run the notebook. 
-- 3. When the notebook run is completed, return to your lakehouse and refresh your materialized lake views graph. 


-- CELL ********************

-- MAGIC %%pyspark
-- MAGIC 
-- MAGIC 
-- MAGIC from pyspark.sql import functions as F
-- MAGIC from pyspark.sql.functions import col
-- MAGIC spark.conf.set("spark.sql.legacy.parquet.datetimeRebaseModeInRead", "CORRECTED")
-- MAGIC spark.conf.set("spark.sql.legacy.parquet.int96RebaseModeInRead", "CORRECTED")
-- MAGIC spark.conf.set("spark.sql.legacy.parquet.datetimeRebaseModeInWrite", "CORRECTED")
-- MAGIC 
-- MAGIC # Run the query
-- MAGIC result_df = spark.sql("""
-- MAGIC     
-- MAGIC CREATE MATERIALIZED LAKE VIEW IF NOT EXISTS pmt_lakehouse.wma_staging.atis_waterjob_combined_pa_mv_ael
-- MAGIC AS
-- MAGIC SELECT
-- MAGIC     UNIQUEID,
-- MAGIC     VFCBCOBJECTID,
-- MAGIC     AUTHORIZATIONID,
-- MAGIC     VFCTRACKING_NUMBER,
-- MAGIC     WATEROBJECTID,
-- MAGIC     JOBNUMBER,
-- MAGIC     FILENUMBER,
-- MAGIC     LICENCENUMBER,
-- MAGIC     VFCAPPSTATUS,
-- MAGIC     ATSAUTHORIZATIONSTATUS,
-- MAGIC     WATERJOBSTATUS,
-- MAGIC     VFCBCJOBSTATUS,
-- MAGIC     STATUSTRANSFORMED,
-- MAGIC     JOBSTATUSGROUP,
-- MAGIC     APPJOBOPEN,
-- MAGIC     APPROVALLICENCESTATUS,
-- MAGIC     REGION,
-- MAGIC     REGIONTRANSFORMED,
-- MAGIC     VFCBCOFFICE,
-- MAGIC     WATEROFFICE,
-- MAGIC     DISTRICTPRECINCT,
-- MAGIC     JOBTYPE,
-- MAGIC     JOBSUBTYPE,
-- MAGIC     JOBTYPETRANSFORMED,
-- MAGIC     JOBTYPEGROUP,
-- MAGIC     CLIENTNAME,
-- MAGIC     WATERSHEDNAME,
-- MAGIC     USETYPE,
-- MAGIC     DIVERSIONTYPE,
-- MAGIC     CIATYPE,
-- MAGIC     DIVERSIONSOURCE,
-- MAGIC     PURPOSEUSENAME,
-- MAGIC     PURPOSEUSECODE,
-- MAGIC     RECEIVEDDATE,
-- MAGIC     FCBCACCEPTEDDATE,
-- MAGIC     FCBCCOMPLETEDATE,
-- MAGIC     FCBCPROCESSINGTIME,
-- MAGIC     FNCONSULTTIME,
-- MAGIC     FNCONSULTCOMPLETE,
-- MAGIC     PROCESSSTATUS,
-- MAGIC     PRELIMREVIEWCOMPLETEDATE,
-- MAGIC     PRELIMREVIEWNETTIME,
-- MAGIC     TECHASSESSMENTCOMPLETEDATE,
-- MAGIC     TECHASSESSMENTNETTIME,
-- MAGIC     LEGALCHECKCOMPLETEDATE,
-- MAGIC     LEGALCHECKCOMPLETENETTIME,
-- MAGIC     GRANTEDREFUSEDATE,
-- MAGIC     GRANTREFUSECOMPLETENETTIME,
-- MAGIC     ATSDECISIONDATE,
-- MAGIC     TOTALTIMEFORDECISION,
-- MAGIC     CURRENTPARKTIME,
-- MAGIC     TOTALPARKTIME,
-- MAGIC     NETTIMEFORDECISION
-- MAGIC FROM pmt_lakehouse.wma_replication.atis_waterjob_combined_mv;
-- MAGIC """)
-- MAGIC 
-- MAGIC # Show results
-- MAGIC result_df.show()

-- METADATA ********************

-- META {
-- META   "language": "python",
-- META   "language_group": "synapse_pyspark"
-- META }

-- MARKDOWN ********************

